## 使用promise进行错误处理

### 隐式try..catch

### 再次抛出

如果处理error正常完成,那么它将继续到最近的成功的.then处理程序

### 未处理的rejection

### 总结

- .catch处理promise中的各种error
- 不使用catch也行

